# Site settings
title: 
header-img: img/home-bg.png
email: sweeneyjered@gmail.com
copyright_name: JDSweeney1
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JDSweeney1
learn_profile: JDSweeney1
email_username: sweeneyjered@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
